# Select flavor,'rhui', etc.
FLAVOR	?= default
DOC_NAME	?= $(NAME)
TEMPLATES_TOPDIR	?= /usr/share/rst2pdf/templates

TEMPLATES_DIR ?= $(TEMPLATES_TOPDIR)/$(FLAVOR)

bootstrap:
ifeq ($(DOC_NAME),)
	@echo "Please set DOC_NAME (make -C ... DOC_NAME=... )"
else
	docutils-exts-bootstrap $(DOC_NAME) $(TEMPLATES_DIR)
endif

.PHONY: bootstrap
