# Select flavor,'rhui', etc.
FLAVOR	?= default

bootstrap:
if ($(DOC_NAME),)
	@echo "Please set DOC_NAME (make -C ... DOC_NAME=... )"
else
	docutils-exts-bootstrap -w ./ -D $(DOC_NAME) -t $(FLAVOR)
endif

.PHONY: bootstrap
